version: "2"

run:
  timeout: 5m
  modules-download-mode: vendor

formatters:
  enable:
    - gofmt
    - goimports

linters:
  default: standard
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - testifylint
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace

  settings:
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 3
      min-occurrences: 3
    dupl:
      threshold: 150
    exhaustive:
      default-signifies-exhaustive: true
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
    nakedret:
      max-func-lines: 30

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  sort-order:
    - file
